club-unit/unit-frontend-cra

- src/components/common/ContentEditor.tsx
작성자: @hoon5083
- 이미지 제한 15MB로 증가
> 이미지 용량 제한 증가

- src/App.tsx
- src/components/common/IconWithText.tsx
- src/components/common/UserCard.tsx
- src/components/common/UserHeader.tsx
- src/components/pages/posts/index/CommentElement.tsx
- src/components/pages/posts/index/PostHeaderSection.tsx
- src/constants/routes.ts
- src/pages/users/[id].tsx
- src/pages/users/me.tsx
- src/types/api/profile.ts
- src/types/api/user.ts
- 프로필 페이지 추가
- 프로필 이동 링크 추가
- 관련 레이아웃 픽스
> 프로필 페이지 추가

- src/App.tsx
- src/components/common/Footer.tsx
- src/pages/privacy.tsx
- footer 레이아웃 수정
- 개인정보처리방침 등 추가
> footer 수정

- src/App.tsx
작성자: @hoon5083
- 모든 페이지 이동시 스크롤 맨 위로 이동
> 페이지 이동시 스크롤 초기화

- src/components/common/UserHeader.tsx
- src/pages/users/[id].tsx
- 프로필 페이지 url 로 접근시 무조건 마이페이지로 이동하는 문제 수정
- 자기 프로필 페이지 접근으로 마이페이지 리디렉션 후 빠져 나올 수 없는 문제 수정
> 프로필 페이지 리디렉션 문제 수정

- src/components/common/Footer.tsx
- 회장 이름 및 연락처 변경
- footer 레이아웃 모바일 대응
> 74기 책임자 정보 수정

- package-lock.json
- package.json
- src/App.tsx
- src/components/common/InfoBanner.tsx
- src/components/common/InfoSection.tsx
- src/constants/routes.ts
- src/mockups/info.ts
- src/pages/index.tsx
- src/types/api/notice.ts
- info banner, info section 추가 및 적용
- 백엔드 형식에 맞춰 데이터 타입 수정 필요
> info banner section 추가

- src/components/common/InfoSection.tsx
- src/constants/routes.ts
> notice api route 변경

- src/constants/routes.ts
> form 머지 오류 수정

- src/components/common/ContentHeaderSection.tsx
- src/components/pages/forms/FormSectionStep.tsx
- src/components/pages/forms/FormWrapperSection.tsx
- src/constants/routes.ts
- src/pages/forms/[id].tsx
> Deploy <1.16>

- src/components/common/InfoBanner.tsx
- src/components/common/withAuth.tsx
- src/components/pages/forms/FormQuestionCard.tsx
- src/pages/forms/[id].tsx
- 공지 배너 및 폼 질문 줄바꿈
- 권한 관련 리디렉션
> 줄바꿈 관련 수정 및 리디렉션 수정

- src/App.tsx
- src/components/common/InfoSection.tsx
- src/components/pages/applications/ApplicationBranchSection.tsx
- src/components/pages/applications/ApplicationsTableSection.tsx
- src/constants/application.ts
- src/constants/routes.ts
- src/pages/applications.tsx
- src/types/api/application.ts
- 가입신청서 view 추가
- 가입신청 상태 변경 API 연결
> 가입신청서 확인 페이지 추가

- src/components/pages/applications/ApplicationsTableSection.tsx
- src/constants/application.ts
- src/pages/applications.tsx
- 본인 지구대 우선 표시 추가
- 상태별 드롭다운 선택 옵션 조정
- 탈락 -> 불합격 워딩 수정
- 지원 시간 추가
> 가입 신청서 조회 페이지 수정

- src/components/pages/applications/ApplicationsTableSection.tsx
- src/components/pages/forms/FormWrapperSection.tsx
- 가입 신청시 중복 등록 문제 수정
- 신청서 시간 표기 수정
- 신청서 순번 수정
> 가입 신청 관련 수정

- src/components/pages/applications/ApplicationOrderSection.tsx
- src/components/pages/applications/ApplicationsStatisticsSection.tsx
- src/components/pages/applications/ApplicationsTableSection.tsx
- src/constants/application.ts
- src/pages/applications.tsx
- src/types/applications.ts
- 통계 카드 추가
- 정렬 기준 선택 추가
- 상태 변경 관련 모달 추가
> 지원 목록 페이지 수정

- src/components/pages/applications/ApplicationsTableSection.tsx
> 지원 목록 페이지 모달 수정

- src/components/pages/forms/FormQuestionCard.tsx
- src/components/pages/register/FormSection.tsx
- 회원가입시 비밀번호 확인 추가
- 폼 작성시 글자수 제한 validation 추가
> 회원가입 및 폼 수정

- package-lock.json
- package.json
- src/components/common/ContentEditor.tsx
- src/components/pages/[slug]/PostListBottomSection.tsx
- src/components/pages/[slug]/PostListCategorySection.tsx
- src/components/pages/posts/index/PostEditSection.tsx
- src/components/pages/posts/index/PostHeaderSection.tsx
- src/constants/routes.ts
- src/contexts/auth/AuthProvider.tsx
- src/pages/[slug]/index.tsx
- src/types/api/post.ts
- src/types/api/profile.ts
- src/types/api/user.ts
- src/utils/common/clientAxios.tsx
- src/utils/users/getPersonalItems.tsx
> v2 적용중 발생 문제 수정

- src/components/common/UserCard.tsx
- src/components/pages/[slug]/PostListBottomSection.tsx
- src/components/pages/[slug]/PostListMobileSection.tsx
- src/components/pages/[slug]/PostListTableSection.tsx
- src/components/pages/forms/FormQuestionCard.tsx
- src/components/pages/forms/FormSectionStep.tsx
- src/components/pages/index/BranchSection.tsx
- src/components/pages/posts/index/PostHeaderSection.tsx
- src/components/pages/users/BadgeCard.tsx
- src/components/pages/users/BasicInfoCard.tsx
- src/pages/users/[id].tsx
- src/utils/common/dateToString.ts
작성자: @kanghoon-dev 
- 프로필 사진 업로드 메소드 변경
- map 함수 내부 key 추가
- Link 컴포넌트 적용
- dateToString 함수 옵션추가
- useLayoutEffect 일부 적용
> v2 전환 중 문제사항 픽스 및 기타 수정

- src/components/common/ContentEditor.tsx
- src/index.css
작성자: @kanghoon-dev 
Related to TSK-60
- 사진 가운데 정렬 문제 수정
- 사진 용량 제한 낮춤
> 이미지 가운데 정렬 문제 수정

- src/components/common/ContentEditor.tsx
> 이미지 크기 감소 완화

- src/components/common/ContentEditor.tsx
- src/index.css
> Deploy <2.0.1>

- src/components/common/ContentEditor.tsx
- src/index.css
> Deploy <2.0.2>

- src/components/common/ContentEditor.tsx
> 이미지 리사이징 수정...re

- src/components/common/ContentEditor.tsx
- src/components/common/NotificationElement.tsx
- src/components/common/NotificationPopup.tsx
- src/pages/[slug]/[Id].tsx
작성자: @kanghoon-dev 
Related to TSK-29
- 이미지 리사이징 추가 (1M 이상에)
- 알림 확인 뮤테이션 추가
> 이미지 리사이징 진짜 추가..및 알림 관련 수정

- src/App.tsx
- src/components/common/Footer.tsx
- src/components/common/NotificationPopup.tsx
- src/components/common/UserCard.tsx
- src/constants/routes.ts
- src/hooks/api/common/useNotificationsNumUnreads.ts
- src/types/api/notification.ts
작성자: @kanghoon-dev 
Related to TSK-88
- 미확인 알림 표시 추가
- 푸터의 TEST 2 텍스트 삭제
> 미확인 알림 뱃지 추가
